In [1]:
import numpy as np
import pandas as pd
import loss_constraint as lc
import pso

In [2]:
import numpy as np
import pandas as pd
import loss_constraint as lc
import algorithm as al 
import matplotlib.pyplot as plt 
import os
from os import walk

data = pd.read_csv(r"E:\python project\production plan\100dataset\dataset\data_103.csv")
data = data.drop(columns= ['Unnamed: 0'],axis = 1)
data['车顶颜色'][data['车顶颜色'] == '无对比颜色'] = data['车身颜色'][data['车顶颜色'] == '无对比颜色']
data 

车型   车身颜色 车顶颜色            物料编号 发动机 变速器
0    A    天空灰   石黑  BZ14GCY0000292  燃油  四驱
1    B  水晶珍珠白   石黑  AZ32GCY0000260  燃油  两驱
2    A    闪耀黑  闪耀黑  AZ62GFF0000250  混动  两驱
3    B    天空灰  天空灰  AZ62GCY0000300  燃油  两驱
4    B    飞行蓝   石黑  AZ62GFF0000252  混动  两驱
..  ..    ...  ...             ...  ..  ..
98   A  水晶珍珠白   石黑  AZ64GCY0000289  燃油  四驱
99   B    飞行蓝   石黑  AZ62GCY0000243  燃油  两驱
100  A    天空灰   石黑  AZ62GFF0000275  混动  两驱
101  A    天空灰   石黑  BZ14GCY0000292  燃油  四驱
102  B    飞行蓝   石黑  AZ62GCY0000243  燃油  两驱

[103 rows x 6 columns]

In [10]:
p_best,g_best_record = pso.PSO(data,100,1,0.5,200,0.85,1,1,0.6,100,20,0.95,-10,10,-1,1)

0  iteration     best loss86367.5
1  iteration     best loss86367.5
2  iteration     best loss86367.5
3  iteration     best loss86367.5
4  iteration     best loss86367.5
5  iteration     best loss86367.5
6  iteration     best loss86367.5
7  iteration     best loss86367.5
8  iteration     best loss86367.5
9  iteration     best loss86367.5
10  iteration     best loss86367.5
11  iteration     best loss86367.5
12  iteration     best loss86367.5
13  iteration     best loss85312.5
14  iteration     best loss85312.5
15  iteration     best loss85312.5
16  iteration     best loss85312.5
17  iteration     best loss85312.5
18  iteration     best loss85312.5
19  iteration     best loss85312.5
20  iteration     best loss85312.5
21  iteration     best loss85312.5
22  iteration     best loss85312.5
23  iteration     best loss85312.5
24  iteration     best loss79676.25
25  iteration     best loss79676.25
26  iteration     best loss79676.25
27  iteration     best loss79676.25
28  iteration     best los

In [11]:
for i in range(0,200):
    print(p_best[i,:])

[ 4.24836941e+00  7.96470543e+00 -3.27752308e+00 -6.26785015e-01
 -2.46160288e+00  7.61894918e+00 -2.14251119e+00  1.60590809e+00
 -6.73223808e+00  6.80171375e+00  5.38717072e+00  3.42345952e-01
  8.97420927e+00  4.94401028e+00  3.69966902e+00  1.35544860e+00
 -8.53347449e+00 -2.66777611e+00  2.56991188e+00 -3.26902035e+00
 -3.56196179e+00  1.78808225e+00 -7.03163267e-01  2.18199250e+00
  1.87552306e+00  4.35237178e+00  4.63634596e+00 -4.57148386e+00
  1.66986019e+00  1.10321478e+00 -3.71460716e+00 -6.25572769e+00
  4.33513089e+00 -2.09603731e+00  1.69422228e+00 -8.28917701e+00
  5.88479243e+00  2.82024301e+00 -2.01481922e+00  7.50337670e-01
 -3.20866503e+00 -8.19651992e+00 -8.53314062e+00  1.55410645e+00
  5.66745504e+00 -8.39622707e+00  8.72275689e+00  5.00969927e-01
 -9.71925007e-01  2.12824963e+00 -4.12532662e+00 -4.82450879e+00
 -2.28257744e-01  7.88999805e+00  5.60013063e+00  2.69933408e+00
 -4.37259594e+00 -1.22906191e+00  3.82688927e-01 -6.88100923e+00
  3.06539176e+00  4.19652

IndexError: index 100 is out of bounds for axis 0 with size 100

In [8]:
np.random.rand(10,5)

array([[0.25553345, 0.12956976, 0.25197873, 0.75798097, 0.13084904],
       [0.43722194, 0.60611078, 0.55930513, 0.17422226, 0.31768418],
       [0.36291195, 0.84517761, 0.9863496 , 0.98150479, 0.33648091],
       [0.81919559, 0.92360217, 0.69333575, 0.40217118, 0.34562418],
       [0.55794318, 0.70161053, 0.31292321, 0.25126133, 0.81121548],
       [0.94755012, 0.98901092, 0.75082872, 0.11814926, 0.7926117 ],
       [0.25797461, 0.02900789, 0.48049707, 0.72161877, 0.91133542],
       [0.09224892, 0.04398801, 0.75656159, 0.92273773, 0.19091484],
       [0.89016024, 0.34517333, 0.21583611, 0.55859281, 0.31335949],
       [0.94173245, 0.78640888, 0.72353293, 0.1879417 , 0.34944444]])

In [7]:
np.broadcast_to(np.random.rand(10,1),(10,5))

array([[0.18727714, 0.18727714, 0.18727714, 0.18727714, 0.18727714],
       [0.31904994, 0.31904994, 0.31904994, 0.31904994, 0.31904994],
       [0.64794595, 0.64794595, 0.64794595, 0.64794595, 0.64794595],
       [0.82543311, 0.82543311, 0.82543311, 0.82543311, 0.82543311],
       [0.96267676, 0.96267676, 0.96267676, 0.96267676, 0.96267676],
       [0.47272143, 0.47272143, 0.47272143, 0.47272143, 0.47272143],
       [0.37302514, 0.37302514, 0.37302514, 0.37302514, 0.37302514],
       [0.48668284, 0.48668284, 0.48668284, 0.48668284, 0.48668284],
       [0.57145982, 0.57145982, 0.57145982, 0.57145982, 0.57145982],
       [0.49537682, 0.49537682, 0.49537682, 0.49537682, 0.49537682]])

In [8]:
np.minimum(p_best, -np.Inf)

array([[-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       ...,
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf],
       [-inf, -inf, -inf, ..., -inf, -inf, -inf]])